/*
* generated by Xtext
*/
package de.sebastianbenz.xgherkin;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class GherkinUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return de.sebastianbenz.xgherkin.ui.internal.GherkinActivator.getInstance().getInjector("de.sebastianbenz.xgherkin.Gherkin");
	}
	
}
