/*
* generated by Xtext
*/
package de.sebastianbenz.xgherkin.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class GherkinAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("de/sebastianbenz/xgherkin/parser/antlr/internal/InternalGherkin.tokens");
	}
}
