/*
* generated by Xtext
*/
package de.sebastianbenz.xgherkin.ui.labeling;

import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;

import com.google.inject.Inject;

import de.sebastianbenz.xgherkin.gherkin.Step;

/**
 * Provides labels for a EObjects.
 * 
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#labelProvider
 */
public class GherkinLabelProvider extends DefaultEObjectLabelProvider {

	@Inject
	public GherkinLabelProvider(AdapterFactoryLabelProvider delegate) {
		super(delegate);
	}
	
	String text(Step step){
		if(step.getDesc().isEmpty()){
			return "<empty>";
		}else{
			return step.getDesc().get(0);
		}
	}

/*
	//Labels and icons can be computed like this:
	
	String text(MyModel ele) {
	  return "my "+ele.getName();
	}
	 
    String image(MyModel ele) {
      return "MyModel.gif";
    }
*/
}
