/*
* generated by Xtext
*/
package de.sebastianbenz.xgherkin.ui.contentassist;

import de.sebastianbenz.xgherkin.ui.contentassist.AbstractGherkinProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class GherkinProposalProvider extends AbstractGherkinProposalProvider {

}
