/*
 * generated by Xtext
 */
package de.sebastianbenz.xgherkin;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class GherkinRuntimeModule extends de.sebastianbenz.xgherkin.AbstractGherkinRuntimeModule {

}
